### ISSUE TITLE
Using non public scheme for Postgres leads to fatal jira ERROR

### ISSUE THREAD

**Issue by stadler-tom** [javimox/helm-charts#45]
When i try to override the "public" scheme for the database connection, 
jira service is unable to start. 
Fatal ERROR: "xyz" schema is not existing. 
FATAL ERROR jira.app_user is missing

**Comment by javimox** [comment]
Hi @stadler-tom,

Thanks for letting me know. The schema in `schemaName` was not being created so Jira crashed.

With the changes on branch **postgres-nonpublic-schema-support** it should work.

However, I am not going to release it since there is an official Jira bug in this regard ([JRASERVER-64886](https://jira.atlassian.com/browse/JRASERVER-64886)), and a workaround is the solution. That, and the Chart can get complex quickly if I keep adding postgresql queries.

If it doesn't work for you with the changes in **postgres-nonpublic-schema-support** feel free to let me know, though.

**Comment by stadler-tom** [comment]
Hi @javimox 

thank you for your reply, i will have a look at it within the next days and give you feedback.

Much appreciation.

**Comment by javimox** [comment]
I close this issue due to inactivity.
